FROM --platform=linux golang:1.18.7-alpine AS builder

ENV COSMOS_VERSION=v0.45.4

RUN apk update
RUN apk add make git

WORKDIR /root
RUN git clone --depth 1 --branch ${COSMOS_VERSION} https://github.com/cosmos/cosmos-sdk.git

WORKDIR /root/cosmos-sdk/cosmovisor

RUN make cosmovisor

FROM --platform=linux checkersd_i:v1-alpine AS v1
FROM --platform=linux checkersd_i:v1.1-alpine AS v1.1
FROM --platform=linux checkersd_i:v2-alpine AS v2
FROM --platform=linux alpine

ENV LOCAL=/usr/local
ENV DAEMON_HOME=/root/.checkers-upgrade
ENV DAEMON_NAME=checkersd
ENV DAEMON_ALLOW_DOWNLOAD_BINARIES=false
ENV DAEMON_RESTART_AFTER_UPGRADE=true

COPY --from=builder /root/cosmos-sdk/cosmovisor/cosmovisor ${LOCAL}/bin/cosmovisor
COPY --from=v1 /usr/local/bin/checkersd $DAEMON_HOME/cosmovisor/genesis/bin/checkersd
COPY --from=v1.1 /usr/local/bin/checkersd $DAEMON_HOME/cosmovisor/upgrades/v1tov1_1/bin/checkersd
COPY --from=v2 /usr/local/bin/checkersd $DAEMON_HOME/cosmovisor/upgrades/v1_1tov2/bin/checkersd

ENTRYPOINT [ "cosmovisor" ]